all:
	python tagcloud.py --out-dir /home/fnargesian/FINDOPENDATA_DATASETS/synthetic/files --dict-file /home/kenpu/clones/tagcloud-nlp-generator/american-english --bin-file /home/kenpu/clones/tagcloud-nlp-generator/data/wiki.en.bin --min-attrs 1 --max-attrs 1

ipython:
	ipython -i itagcloud.py
